- blark/iec.lark
* Conversion tool I had written added extraneous parentheses; trying to reduce them here
* I'm actually trying to use blark for once to parse all declaration blocks into variable/type information for a separate project
* The grammar appears to require some modifications to make the above project feasible
* I've at least run into one additional bug (`fbArbiter : FB_Arbiter(1)` is parsed in a FB vars block but not in a GVL block -> issue)
> MNT: some grammar cleaning and minor fixes

- .gitignore
- MANIFEST.in
- blark/format.py
- blark/iec.lark
- blark/parse.py
- blark/sphinxdomain.py
- blark/summary.py
- blark/tests/conftest.py
- blark/tests/test_parsing.py
- blark/tests/test_transformer.py
- blark/tests/test_util.py
- blark/transform.py
- blark/util.py
* Reworked how `Meta` instances are transferred over from `lark` to `blark`; add explicit dataclass attributes for them
* Trying out a layer that summarizes transformed code for easier access ("tell me the function blocks, their declared variables/methods/actions, and where to find them")
* Building a sphinx Domain on top of it (looking at sphinx-julia, built-in Python support for inspiration/ideas how to do it)
* Rework some weird code flow from the original `blark parse` CLI
* Some test cleanup
* More test coverage for global var declarations
* Made mypy a lot happier for `blark.transform` (never 100% happy of course)
* Add UNION support (Closes #14 )
* Additional grammar fixes (need to document more of the differences noted when running TwinCAT. As to be expected, blark is more …
> ENH: initial attempts at code summary layer, sphinx domain

- .github/workflows/pytest.yml
* Add `.github/workflows/pytest.yml` to define the installation of dependencies and execution of `pytest` to validate behavior.
I'm loving what you've got here in this project, and I want to use it in some of my work, but to do that, I need to enhance a few things. Before I start with too much of that, I wanted to bring in some automated testing to validate changes I make, and prove them out so that you're at least somewhat confident that my changes won't destroy your work.
> Add Github Action to Run Pytest for push/pull-request Actions

- .vscode/settings.json
- MANIFEST.in
- blark/iec.lark
- blark/tests/source/fb_w_public_access.st
- blark/tests/test_parsing.py
- blark/tests/test_transformer.py
- blark/transform.py
* Enhances grammar to qualify function blocks with more broad access specifiers, including:
* ABSTRACT (pre-existing)
* PUBLIC
* PRIVATE
* PROTECTED
* INTERNAL
* FINAL
* Adds tests to validate 61131 source directly, without the use of `*.TcPOU` files.
Please let me know if there are any questions or concerns with the changes! I have a few other enhancements I would like to contribute, and I want to make sure that my contributions are effective, and in-line with the direction you want to maintain.
Thank you so much!
> Enhancement: support access specifiers for function block declarations

- blark/iec.lark
- blark/tests/test_transformer.py
- blark/transform.py
* Add support for POINTER/REFERENCE TO in Union data structures. Example:
```
TYPE TypeName :
UNION
pt_value : POINTER TO INT;
pt_SomethingElse : POINTER TO class_SomethingCool;
END_UNION
END_TYPE
```
I couldn't find a good sample set of documentation for this, but I've used unions for pointer manipulation in a few cases. Most commonly when dealing with dynamic memory allocations. Please let me know if you have any questions about this!
> Add Support of Indirection in Unions

- blark/iec.lark
- blark/tests/test_transformer.py
- blark/transform.py
* Add support for Access Specifier for Functions
* Add support for Access Specifier in Struct/Union/Enum Types
* Add support for Use of Instantiated function-blocks with FB_Init arguments
I'm not absolutely sure that I'm following the correct practice in regards to the addition of `FunctionCall` in the `StructureElementDeclaration` [see here](https://github.com/klauer/blark/compare/master...engineerjoe440:enhancement/func-access_struct-fb-init-args_data-type-access?expand=1#diff-c26321b40313af0a101f2abfe0076eb50f721b233e65e3f5db676c2cbd4054f3R1185). That said, I'm happy to make any adjustments as you see fit! I'm sorry that I couldn't find better references for the use of access specifiers for functions and type declarations. It seems that feature is not very widely documented.
> Enhance: Function and Data Type Access Specifier, and Structures using FB_Init args

- blark/iec.lark
- blark/tests/source/commas_in_case.st
- blark/tests/test_transformer.py
- blark/transform.py
* Add `bit_string_literal` to list of `case_list_elements`
* Add test of CASE with `BYTE#...`
* Add source file to verify CASE in context.
* #34 
This still may be better enhanced by including `boolean_literal`, but I'm not quite sure of that.
> Bugfix/Enhancement: Add Support of `bit_string_literal` in CASE Statements

- blark/iec.lark
- blark/tests/source/array_of_objects.st
- blark/tests/source/pointer_to_pointer_to.st
- blark/tests/source/stray_comment.st
- blark/tests/test_transformer.py
- blark/transform.py
I've found a number of little things that were causing some trouble while I was testing this project against a number of 61131 repositories, I've made a bunch of smaller, incremental branches for each stage of work, so if you'd prefer going through one at a time, let me know!
* Add Support of VAR_EXTERNAL in Functions.
* Allow DateTimes to exclude seconds/fractional-seconds (both appear to be legal options for 61131).
* Support Arrays of FunctionBlocks that use an FB_init inline. [example](https://github.com/engineerjoe440/blark/blob/ecffb0a5ebe4fa2bb5da4f701dd3b6a8932d5a21/blark/tests/source/array_of_objects.st#L4)
* Allow "Stray" semicolons that would otherwise have no effect.
* Allow Namespaced (dotted) access to structures in declaration when setting a default. …
> Enhancements and Fixes Found While Testing Code Base

- blark/tests/test_transformer.py
- blark/transform.py
`IndirectionType.none` went away, but we were still using it in `DataType`.
* Somewhat counter-intuitively, we can get an `IndirectionType` with a pointer depth of 0 and no reference flag set
* So this PR adds a simple property to replace that `none` check (`is_indirect`)
* This can then be used for the round-tripping of the data type
* Added test coverage of the rule
> FIX: small regression after IndirectionType adjustments of #33

- .github/workflows/pytest.yml
- requirements-dev.txt
* Add `requirements-dev` for development requirements
* Modify GitHub actions to cover the blark codebase
* Upload coverage artifacts to GitHub
* Upload coverage report to codecov.io
> CI: code coverage via pytest-cov and codecov

- .github/codecov.yml
- .github/workflows/lint.yml
- .github/workflows/pytest.yml
- blark/transform.py
* Trying to make [mypy](http://mypy-lang.org/) happier on `blark.transform`
* Checking that `(dataclass).from_lark` annotations are correct compared to arguments passed in the test suite
> FIX: further annotation-related fixes

- .github/workflows/lint.yml
- .github/workflows/pre-commit.yml
- .github/workflows/pytest.yml
- .pre-commit-config.yaml
- blark/transform.py
* 3.8 job is failing due to apischema import. I'm unable to reproduce this locally
* Regardless of that failure, we don't want the entire test suite failing
* As such, `fail-fast` was disabled
Separately:
* Deprecated/old reusable jobs were updated
* A pre-commit check job was added (which duplicates some of the linter job, but that's OK for now)
* Fixed pre-commit URL for flake8 (gitlab->github) and excluded the PLC source directories globally
* Added a Python 3.11 job to the matrix
> CI: updates to GitHub Actions and pre-commit fixes

- blark/iec.lark
- blark/tests/source/object_oriented_dotaccess.st
- blark/tests/test_transformer.py
- blark/transform.py
* #54 
* Add support of chained function-call/method-call statements with new `function_call_statement_list` grammar.
I think this is a fairly reasonable way to address this item, but I'm very open to comments or suggestions. I think it's possible to combine the original `function_call_statement` and this new `function_call_statement_list` but I left the original one for consistency sake. Let me know what you think!
> Add Support of Chained Method/Function Calls

- blark/iec.lark
- blark/tests/source/array_initializer.st
- blark/tests/source/fb_initializer.st
- blark/tests/test_transformer.py
- blark/transform.py
* #44
* Add support for array initializer for function-block objects.
* Enhance function-block declaration to support setting structured attributes (`VAR_INPUT` and `VAR_IN_OUT`).
Hopefully with these additions, some of the "in-the-wild" code we've come across will get patched up and parse as we expect. :smile:
> Array Initializer

- blark/iec.lark
- blark/tests/source/dereference_method.st
- blark/tests/test_transformer.py
- blark/transform.py
* #57 
* Added optional dereference (`^`) character to function and method call (return) statements.
These changes should make this all a bit more convenient, and should allow for syntax such as:
```pascal
uut.call1()^.call2(A := 1).call3(B := 2)^.call4().done();
```
Which can allow for chained method calls using dereferences on any returned pointers.
> Support Dereferenced Function/Method Returns in Grammar

- blark/iec.lark
- blark/tests/test_transformer.py
* #58 
* Add optional explicit base-10 specifier for integers.
@klauer, you really made this one too easy! 😉 Thanks, again!
> Support for Explicit Base 10 Integers

- blark/iec.lark
- blark/tests/source/array_with_integer_initializer.st
- blark/tests/test_transformer.py
- blark/transform.py
* #60 
* #61 
* Remove `method_statement` from `iec.lark`
* Remove `MethodStatement` from `blark.transformers`
* Restore previous modification affecting array initialization
TBD
> Address Issue with Array-Initialization -- Other General Cleanup

- blark/iec.lark
- blark/tests/source/array_of_arrays.st
- blark/tests/test_transformer.py
- blark/transform.py
* #65 
* Allow arrays to consist of arrays to support indeterminate nesting (I don't know if there's a compiler-imposed limit, but it certainly makes sense there would be a behavioral limit).
* Add relevant tests to confirm behavior.
I think this one should be pretty simple. I'm thankful for that! No rush to get this merged in (please enjoy your time away and don't review until you return).
> Support arrays of arrays

- blark/iec.lark
- blark/tests/test_transformer.py
* #67 
* Use `+` instead of `*` in `iec.lark` grammar for RETURN statement to require 1 or more semicolons instead of 0 or more.
* Use `+` instead of `*` in `iec.lark` grammar for CONTINUE statement to require 1 or more semicolons instead of 0 or more.
* Tests to validate behavior and appropriate parsing.
* #66 (this PR contains those same changes, so we should probably merge it first 😝 )
This looks like a much simpler change than I had anticipated. Very excited about that! :smile:
> Resolve RETURN and CONTINUE Overly-Greedy Matching

- .github/workflows/pytest.yml
- blark/iec.lark
- blark/tests/conftest.py
- blark/tests/test_transformer.py
- blark/transform.py
Closes #70 
Building on @engineerjoe440 's branch
* CI will only test on Python 3.9+ going forward.
* 3.7 and 3.8 will be considered unsupported - but some/most of blark may still work on them
* Added `bracketed_expression` used solely for string lengths as in `STRING[255]`
* Grammar change - terminal `STRING_TYPE` -> is now a rule `string_type_specification` as it must support expressions for length and not just simple integers/constants/terminals
* `string_spec_length` added to support both flavors of string type declaration lengths `STRING[255]` and `STRING(255)`
* Adjusted dataclasses to support the grammar changes
* `SimpleSpecification` gets a bit more complicated as its type is no longer just a string `Token`
* Added a bunch of TwinCAT-approved string declarations, which went …
> FIX: string length expression

- .github/workflows/pytest.yml
- .gitmodules
- README.md
- blark/__init__.py
- blark/__main__.py
- blark/dependency_store.py
- blark/format.py
- blark/iec.lark
- blark/input.py
- blark/output.py
- blark/parse.py
- blark/plain.py
- blark/solution.py
- blark/summary.py
- blark/tests/conftest.py
- blark/tests/test_cli.py
- blark/tests/test_dependency_store.py
- blark/tests/test_parsing.py
- blark/tests/test_solution.py
- blark/tests/test_summary.py
- blark/tests/test_transformer.py
- blark/tests/test_util.py
- blark/transform.py
- blark/typing.py
- blark/util.py
- requirements.txt
**If this breaks your usage of blark, let me know!**
This is a pretty large refactor/enhancement, comments/ideas/complaints are welcome.
Primarily: to close https://github.com/klauer/blark/issues/53
More specifically (caveat: some goals may be walked back; some may not be written here yet) -
* Continue to support the current input formats (plain text `.st` files, and TwinCAT source code files)
* Remove dependency on pytmc (for code loading, the dependency store, and everything else).
* Require `lxml` for project parsing.
* Make file loading more easily customizable, with the option to load/save arbitrary file formats so long as you can provide an adapter (or for command-line input, code with metadata described by a JSON schema).
* Allow for mapping of blark input line numbers back to …
> REF/ENH: standalone solution parser and rewrite of input/output format support

- blark/iec.lark
- blark/tests/test_transformer.py
- blark/transform.py
> FIX/CLN: remove unsupported power_expression

- blark/iec.lark
- blark/tests/source/array_of_addresses.st
- blark/transform.py
Closes #69 
This relaxes array initial elements to not just being constants, but general expressions.
> FIX: Bugfix for expressions in initial array elements

- blark/iec.lark
- blark/parse.py
- blark/solution.py
- blark/summary.py
- blark/tests/test_summary.py
- blark/tests/test_transformer.py
- blark/transform.py
- blark/util.py
First pass at `INTERFACE` support.
Closes #16 
It wasn't possible to parse `TcIO` files with pytmc previously, but now with our built-in solution parser of #64 we can move forward with supporting interface files directly from TwinCAT projects.
Some additional fixes made their way in here, too.
> ENH: interface support

- blark/solution.py
- blark/tests/test_dependency_store.py
Projects with `GlobalTextList` entries in TwinCAT projects would previously raise:
`RuntimeError: Unsupported xml type for TcSource: <Element TcPlcObject at 0x7f70fc315340>`
For one, that exception message has been improved to include a bit more context:
`UnsupportedSourceFileError: Unsupported xml type for TcSource: TcPlcObject/GlobalTextList`
If loaded directly with the `TcSource.from_filename` utility method, the above will be raised.
If loaded as part of a solution/tsproj, the unsupported source file will just be ignored.
* Update blark-twincat-root project to have some more unsupported file formats (and make sure blark doesn't fall over)
* Fix module-level `pytest.skip` error when users (or I) accidentally forget to clone recursively
* [pcdshub](https://github.com/pcdshub/) …
> FIX: ignore global text list project files

- blark/parse.py
- blark/solution.py
- blark/tests/POUs/FB_Log.TcPOU
- blark/transform.py
* `blark parse --summary` had a bit of trouble with #83 as well as `blark format`, this PR aims to resolve that.
* Despite the issue title, there is no problem with simply parsing the file, but rather filtering it through the summary tools and the reformatting tools
* Added #83 's `FB_Log.TcPOU` with the reporter's approval
* With this PR, I'm able to do this and get a valid reformatted file:
```bash
$ blark parse --summary FB_Log.TcPOU
$ blark format --overwrite FB_Log.TcPOU
```
> FIX: format failure of #83

- .github/workflows/pytest.yml
- blark/iec.lark
- blark/tests/test_transformer.py
- blark/transform.py
- blark/util.py
(This is part of a larger [branch](https://github.com/klauer/blark/compare/master...enh_docs) which got to be unmanageably large - breaking it up into separate PRs)
Fixes:
* Fixes incorrect escape character for double quotes in double-byte strings (`"$""`)
* Don't add more parentheses than required when formatting dataclasses back to code (specifically for `ObjectInitializerArray`)
Clean-up:
* Removed unused grammar rules `structured_var_declaration`, `function_var_decl`, `step_*`, etc.
* Removed grammatical alias `structure_type_name` from `var_spec` (since `simple_spec` covers it just fine)
Test suite:
* More coverage for grammar rules in `test_transformer`
* Coverage check to ensure that all known rules are hit (terminals are a bit buggy there, but I'm not too worried about it)
* This …
> Unused grammar rule clean-up and grammar coverage tests

- blark/__init__.py
- blark/html.py
- blark/tests/test_cli.py
(This is part of a larger [branch](https://github.com/klauer/blark/compare/master...enh_docs) which got to be unmanageably large - breaking it up into separate PRs)
A first pass at allowing blark to output syntax-highlighted (or HTML entity-annotated) code. I anticipated using this in documentation at some point, rather than writing something for [Pygments](https://chiplicity.readthedocs.io/en/latest/Using_Sphinx/ShowingCodeExamplesInSphinx.html#pygments-lexers) 
Things to do, maybe or maybe not in this PR:
A couple interesting notes:
* Stylesheet-wise: if I can make a decent looking theme for the output, I may consider adding some sample CSS as part of the package (but not in each output).
* This currently only works to syntax highlight (well, add tags with defined HTML classes - the …
> ENH: first pass at html output

- .github/workflows/docs.yml
- .github/workflows/pytest.yml
- docs/source/conf.py
- requirements-doc.txt
- setup.py
* Add "extras" to blark's installation `pip install blark[dev]` (apischema + pytest) or `pip install blark[doc]` (dev deps + sphinx and such)
* I'm considering making apischema an install requirement (#91)
* Add CI workflow for building and deploying docs
* Add lark/Python as intersphinx targets (for cross-linking API docs of lark/standard lib classes/functions)
* Use a token with codecov as it started complaining in the pytest workflow
> CI: documentation deployment GitHub Action

- .github/workflows/docs.yml
- blark/iec.lark
- blark/tests/test_transformer.py
- blark/transform.py
Closes #93 
* Expressions may include chained function calls
* Prior to this PR, only statements defined in such a way were supported
* Adds `chained_function_call` grammar rule and `ChainedFunctionCall` class
> FIX: function call chaining in expressions

- blark/iec.lark
- blark/tests/test_transformer.py
- blark/transform.py
> FIX: init arguments for pointer type specifications

- blark/iec.lark
- blark/tests/source/enum_with_function_calls.st
- blark/transform.py
- Closes: #103 
Resolves issues with the grammar to allow enumeration defaults to use function calls.
> Enhance Grammar to Support Enumeration Default Values Defined by Functions

- blark/iec.lark
- blark/tests/source/var_declarations_var_attrib.st
- blark/tests/test_transformer.py
Closes #106  (or hopes to)
The example provided in the issue report, which made it into this PR as a test suite example:
```
PROGRAM Test
VAR CONSTANT
RetainInt: INT;
END_VAR
VAR RETAIN
constantInt: INT;
END_VAR
END_PROGRAM
```
Shows how blark's rather lax whitespace-handling rules can be excessively so. What happened, prior to this PR, was that `VAR CONSTANT` would see the keyword `Retain` and add that to the list of access modifiers (i.e., `VAR CONSTANT RETAIN` and the variable would then be `Int`). 
In truth, I had seen this once before a year or so ago and didn't pursue a real fix.
The fix is simply to ensure that there are word boundary markers in the regular expressions for each keyword (`\b` before and after the keyword text).
Doing this in-place would have required changing the …
> FIX: a sweeping fix for keyword word boundary handling

- blark/iec.lark
- blark/tests/test_parsing.py
- blark/transform.py
Fixes #108. I also added a test that verifies some basic expectations about the parsing of boolean literals. It does so by checking that some key token (e.g. _constant_, _TRUE_VALUE_) can be found somewhere in the parse tree. The test is parametrized so that it can be reused for further checks of a similar kind.
> Increase priority of constant rule in grammar (#108)
